# Import the required libraries:


In [103]:
import numpy as np
import pandas as pd

# Generate sample data
# Create a two features data, here naming X and Y of size 100 samples.


In [104]:
np.random.seed(0) # Configuration for random number
data = pd.DataFrame(np.random.randn(100,2), columns=['X', 'Y'])
print(data)

           X         Y
0   1.764052  0.400157
1   0.978738  2.240893
2   1.867558 -0.977278
3   0.950088 -0.151357
4  -0.103219  0.410599
..       ...       ...
95 -1.292857  0.267051
96 -0.039283 -1.168093
97  0.523277 -0.171546
98  0.771791  0.823504
99  2.163236  1.336528

[100 rows x 2 columns]


# Calculate covariance matrix


In [105]:
cov_matrix = np.cov(data['X'], data['Y'])
cov_matrix

array([[ 1.05494742, -0.02517201],
       [-0.02517201,  1.04230397]])

# Extract covariance 
# b and c element represent covariance

In [106]:

covariance = cov_matrix[0, 1]
covariance


-0.02517201366023152

# Calculate correlation matrix:

In [107]:
cor_matrix = np.corrcoef(data['X'], data['Y'])
cor_matrix

array([[ 1.       , -0.0240052],
       [-0.0240052,  1.       ]])

# Extract correlation coefficient:

In [108]:
correlation = cor_matrix[0, 1]
correlation

-0.02400520149407843

# Import required libraries for visualization and statistics. (matplotlib and seaborn).

In [109]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create a function to draw a box plot:


In [110]:
def create_box_plot(data1):
    plt.figure(figsize=(8,6))
    sns.boxplot(data=data1)
    plt.title('Box Plot')
    plt.xlabel('Data')
    plt.ylabel('Values')
    plt.show()

# Example data:

In [111]:
data1 = {
    'Group A': [-1, 12, 15, 18, 20, 22], # add -1 and see outlier
    'Group B': [11, 14, 17, 20, 23, 26],
    'Group C': [8, 10, 12, 14, 16, 18]
}


# Draw the box plot:

In [112]:
# Some KeyError is coming, TODO later:
# create_box_plot(data1)

# Perform correlation and covariance on a class problem:

In [113]:
x = np.array([30, 35, 40, 25, 35])
y = np.array([5, 8, 8, 4, 5])

In [114]:
cor_matrix = np.corrcoef(x, y)
cor_matrix

array([[1.        , 0.82041265],
       [0.82041265, 1.        ]])

In [115]:
cov_matrix = np.cov(x, y)
cov_matrix

array([[32.5 ,  8.75],
       [ 8.75,  3.5 ]])

# Maths and physics correlation problem:

In [116]:
data_calories = pd.read_csv("data.csv")

# Display the data:

In [117]:
data_calories.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

# Perform correlation operation:

In [118]:
cor_matrix = np.corrcoef(data_calories['Pulse'], data_calories['Maxpulse'])
cor_matrix

array([[1.        , 0.78653468],
       [0.78653468, 1.        ]])

# Perform covariance operation:

In [119]:
cov_matrix = np.cov(data_calories['Pulse'], data_calories['Maxpulse'])
cov_matrix

array([[210.54761905, 187.74587912],
       [187.74587912, 270.61679346]])

# Pandas function for correlation:

In [120]:
df = pd.DataFrame(data_calories)
df.corr()

Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

# Pandas function for covariance:


In [121]:
df.cov()

Duration       Pulse    Maxpulse      Calories
Duration   1789.285714  -95.386905    6.543040  10541.779964
Pulse       -95.386905  210.547619  187.745879     97.950816
Maxpulse      6.543040  187.745879  270.616793    900.323552
Calories  10541.779964   97.950816  900.323552  70958.261377